### ISSUE TITLE
Cannot start normally after stop

### ISSUE THREAD

**Issue by biluohc** [nervosnetwork/ckb#3048]
### Current Behavior

Cannot start normally after ctrlc

### Environment

- **CKB version**:  v100
- **Chain**: testnet
- **Operating system**: Ubuntu 16.04
- **Arch**: x86_64
- **Installation**: Built from source

### Additional context/Screenshots

```sh
021-09-22 15:50:04.863 +08:00 ChainService INFO ckb_chain::chain  block: 6580, hash: 0x684988dd04e5db3543cc4b2b2f8364e4611a85ab247d96e46a03f3477e25ed30, epoch: 10(288/608), total_diff: 0x451fed9f4a, txs: 1
^C2021-09-22 15:50:05.067 +08:00 main INFO ckb_bin::subcommand::run  Finishing work, please wait...
2021-09-22 15:50:05.067 +08:00 main INFO ckb_tx_pool::service  Please be patient, tx-pool are saving data into disk ...
:/opt/ckb/ckb-testnet#
:/opt/ckb/ckb-testnet# ./ckb run
2021-09-22 15:50:11.734 +08:00 main INFO ckb_bin::helper  raise_fd_limit newly-increased limit: 65535
2021-09-22 15:50:11.880 +08:00 main INFO ckb_bin::subcommand::run  ckb version: 0.100.0 (c978940 2021-09-13)
2021-09-22 15:50:12.317 +08:00 main ERROR panic  thread 'main' panicked at 'db operation should be ok: Error { kind: Internal, inner: Database(Corruption: Unsupported compression method or corrupted compressed block contents: Snappy) }': store/src/db.rs:41   0: ckb_logger_service::setup_panic_logger::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <ckb_store::db::ChainDB as ckb_store::store::ChainStore>::get
   8: ckb_store::store::ChainStore::get_block_header
   9: ckb_store::store::ChainStore::get_tip_header
  10: ckb_launcher::shared_builder::SharedBuilder::build
  11: ckb_launcher::Launcher::build_shared
  12: ckb_bin::subcommand::run::run
  13: ckb_bin::run_app
  14: ckb::main
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: std::rt::lang_start::{{closure}}
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  18: main
  19: __libc_start_main
  20: _start

:/opt/ckb/ckb-testnet#
```

**Comment by driftluo** [comment]
https://github.com/nervosnetwork/ckb-docker-builder/blob/master/bionic/Dockerfile#L1

The minimum version we support is 18.04, 16.04 has not been tested, by the way, this behavior cannot be reproduced on 18.04 and archlinux
