### ISSUE TITLE
Unit tests Failures on `ci_unit_test_windows`

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/ckb#4005]
There are some unit tests that did not pass on `ci_unit_test_windows`. Here are the details for the specific failures:

1. Test `ckb-chain::block_assembler::test_candidate_uncles_retain` failed with the following error:
https://github.com/nervosnetwork/ckb/actions/runs/5197451244/jobs/9372317866
```
       ABORT [   1.333s] ckb-chain tests::block_assembler::test_candidate_uncles_retain
     Message [         ] code 0xc0000005: Invalid access to memory location. (os error 998)

--- STDOUT:              ckb-chain tests::block_assembler::test_candidate_uncles_retain ---
```
2. In the `ckb-network::protocols::tests::test_dial_all` function, the test may be stuck at either `net_service_start` or `node1.dial(&node2, TargetProtocol::All)`, preventing the unit test from exiting.
https://github.com/nervosnetwork/ckb/blob/ed80d4d195fb5757e2fbab40aea007eb4c9afc03/network/src/protocols/tests/mod.rs#L550-L569

These issues need to be investigated further to determine the underlying causes of the failures.

**Comment by eval-exec** [comment]
https://github.com/nervosnetwork/ckb/actions/runs/5330025936/jobs/9656294702

**Comment by eval-exec** [comment]
https://github.com/nervosnetwork/ckb/actions/runs/5408044696/jobs/9826716994

**Comment by eval-exec** [comment]
https://github.com/nervosnetwork/ckb/actions/runs/5816401584/job/15769444864

<details>
<code>
--- STDERR:              ckb-network protocols::tests::test_dont_reset_peer_flags_on_disconnect ---
thread 'protocols::tests::test_dont_reset_peer_flags_on_disconnect' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `63`', network\src\protocols\tests\mod.rs:719:13
stack backtrace:
   0:     0x7ff6f20a6052 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6f20a6052 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6f20a6052 - std::sys_common::backtrace::_print_fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff6f20a6052 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff6f20c975b - core::fmt::write
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\fmt\mod.rs:1208
   5:     0x7ff6f209d93a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\io\mod.rs:1682
   6:     0x7ff6f20a5d9b - std::sys_common::backtrace::_print
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff6f20a5d9b - std::sys_common::backtrace::print
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff6f20a8ec9 - std::panicking::default_hook::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:267
   9:     0x7ff6f20a8b4b - std::panicking::default_hook
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:286
  10:     0x7ff6f20a9761 - std::panicking::rust_panic_with_hook
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:688
  11:     0x7ff6f20a94ee - std::panicking::begin_panic_handler::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:579
  12:     0x7ff6f20a6d4f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:137
  13:     0x7ff6f20a91a0 - std::panicking::begin_panic_handler
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
  14:     0x7ff6f2112585 - core::panicking::panic_fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
  15:     0x7ff6f21128f5 - core::fmt::Arguments::new_v1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\fmt\mod.rs:398
  16:     0x7ff6f21128f5 - core::panicking::assert_failed_inner
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:245
  17:     0x7ff6f1f66dca - core::panicking::assert_failed<u64,u64>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\panicking.rs:199
  18:     0x7ff6f174883c - ckb_network::protocols::tests::test_dont_reset_peer_flags_on_disconnect::closure$0
                               at C:\Users\Administrator\actions-runner\windows-runner-1\_work\ckb\ckb\network\src\protocols\tests\mod.rs:719
  19:     0x7ff6f17a514f - ckb_network::protocols::tests::test_dont_reset_peer_flags_on_disconnect
                               at C:\Users\Administrator\actions-runner\windows-runner-1\_work\ckb\ckb\network\src\protocols\tests\mod.rs:724
  20:     0x7ff6f1748688 - ckb_network::protocols::tests::test_dont_reset_peer_flags_on_disconnect::closure$0
                               at C:\Users\Administrator\actions-runner\windows-runner-1\_work\ckb\ckb\network\src\protocols\tests\mod.rs:689
  21:     0x7ff6f18001b2 - core::ops::function::FnOnce::call_once<ckb_network::protocols::tests::test_dont_reset_peer_flags_on_disconnect::closure_env$0,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
  22:     0x7ff6f1ad6b5f - core::ops::function::FnOnce::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:507
  23:     0x7ff6f1ad6b5f - test::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::string::String> >,enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)()>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:657
  24:     0x7ff6f1a9ec60 - test::run_test::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:648
  25:     0x7ff6f1a9ec60 - core::ops::function::FnOnce::call_once<test::run_test::closure_env$1,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:507
  26:     0x7ff6f1ad53bd - alloc::boxed::impl$45::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2000
  27:     0x7ff6f1ad53bd - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panic\unwind_safe.rs:271
  28:     0x7ff6f1ad53bd - std::panicking::try::do_call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:483
  29:     0x7ff6f1ad53bd - std::panicking::try
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:447
  30:     0x7ff6f1ad53bd - std::panic::catch_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panic.rs:137
  31:     0x7ff6f1ad53bd - test::run_test_in_process
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:680
  32:     0x7ff6f1ad53bd - test::run_test::run_test_inner::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:574
  33:     0x7ff6f1a95f3a - test::run_test::run_test_inner::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\test\src\lib.rs:601
  34:     0x7ff6f1a95f3a - std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::run_test_inner::closure_env$1,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:121
  35:     0x7ff6f1a9ef3b - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\thread\mod.rs:550
  36:     0x7ff6f1a9ef3b - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panic\unwind_safe.rs:271
  37:     0x7ff6f1a9ef3b - std::panicking::try::do_call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:483
  38:     0x7ff6f1a9ef3b - std::panicking::try
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:447
  39:     0x7ff6f1a9ef3b - std::panic::catch_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panic.rs:137
  40:     0x7ff6f1a9ef3b - std::thread::impl$0::spawn_unchecked_::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\thread\mod.rs:549
  41:     0x7ff6f1a9ef3b - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<test::run_test::run_test_inner::closure_env$1,tuple$<> >,tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:507
  42:     0x7ff6f20b6dcc - alloc::boxed::impl$45::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2000
  43:     0x7ff6f20b6dcc - alloc::boxed::impl$45::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\alloc\src\boxed.rs:2000
  44:     0x7ff6f20b6dcc - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys\windows\thread.rs:56
  45:     0x7fff6c2b7974 - BaseThreadInitThunk
  46:     0x7fff6ca3a2f1 - RtlUserThreadStart

</code>
</details>
