### ISSUE TITLE
Integration test failure: `RbfRejectReplaceProposed` with approximately `1%` occurrence rate

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/ckb#4180]
## Bug Report

`RbfRejectReplaceProposed` failed on Integration test, this happens with approximately 1% occurrence rate.
### Environment

- **CKB version**:  [latest develop branch](https://github.com/nervosnetwork/ckb/tree/45104e08c18852260282f23858ce21afae4c9f34)
- **Chain**: /
- **Operating system**: `NixOS 23.11`
- **Arch**: x64 
- **Installation**: Built from source

### Additional context/Screenshots

I can reproduce this by:
```bash
$ while true; do CKB_TEST_ARGS="RbfRejectReplaceProposed" make integration; done
git submodule update --init
cp -f Cargo.lock test/Cargo.lock
cargo build --release --features deadlock_detection,with_sentry
    Finished release [optimized] target(s) in 0.25s
RUST_BACKTRACE=1 RUST_LOG=info,ckb_test=debug,ckb_sync=debug,ckb_relay=debug,ckb_network=debug test/run.sh -- --bin "/home/exec/Projects/github.com/nervosnetwork/ckb/target/release/"ckb"" -c 4 RbfRejectReplaceProposed
    Updating `tuna` index
    Finished release [optimized] target(s) in 0.38s
     Running `target/release/ckb-test --bin /home/exec/Projects/github.com/nervosnetwork/ckb/target/release/ckb -c 4 RbfRejectReplaceProposed`
2023-10-09 05:41:43.663 +00:00 main INFO ckb_test  binary: /home/exec/Projects/github.com/nervosnetwork/ckb/target/release/ckb
2023-10-09 05:41:43.663 +00:00 main INFO ckb_test  vendor dir: /home/exec/Projects/github.com/nervosnetwork/ckb/test/vendor
2023-10-09 05:41:43.663 +00:00 main INFO ckb_test  start port: 9000
2023-10-09 05:41:43.663 +00:00 main INFO ckb_test  max time: 0
2023-10-09 05:41:43.664 +00:00 main INFO ckb_test  start 1 workers...
2023-10-09 05:41:43.664 +00:00 main INFO ckb_test  [RbfRejectReplaceProposed] Start executing
2023-10-09 05:41:43.664 +00:00 *unnamed* INFO ckb_test::node  working_dir "/run/user/1000/ckb-it-RbfRejectReplaceProposed-node0-99XzK9"
2023-10-09 05:41:45.430 +00:00 *unnamed* ERROR panic  thread 'unnamed' panicked at 'tx1 should be proposed': src/specs/tx_pool/replace.rs:476   0: ckb_logger_service::setup_panic_logger::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1999:9
      std::panicking::rust_panic_with_hook
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:709:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:595:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
   4: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   5: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   6: <ckb_test::specs::tx_pool::replace::RbfRejectReplaceProposed as ckb_test::specs::Spec>::run
   7: ckb_test::worker::Worker::run_spec
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys/unix/thread.rs:108:17
  11: start_thread
  12: __clone3

2023-10-09 05:41:45.431 +00:00 *unnamed* DEBUG ckb_test::node  Successfully killed ckb process (RbfRejectReplaceProposed_node0)
--------------------
TEST                                                              | STATUS     | DURATION
RbfRejectReplaceProposed                                          | Failed     | 1 s
Total elapsed time: 1.776174823s

```

**Comment by doitian** [comment]
Need to evaluate the impact before #4181
