### ISSUE TITLE
`ckb-chain tests::dep_cell::test_package_txs_with_deps` failed on MacOS CI workflow

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/ckb#4207]
## Bug Report
On develop branch's merge queue CI workflow, commit [5975fda61bd3a03ec2a4a6075a4e627f185b4d2f](https://github.com/nervosnetwork/ckb/tree/5975fda61bd3a03ec2a4a6075a4e627f185b4d2f),  unit test: `test_package_txs_with_deps` failed. https://github.com/nervosnetwork/ckb/actions/runs/6639559667/job/18038179855

```
FAIL [ 121.180s] ckb-chain tests::dep_cell::test_package_txs_with_deps

--- STDOUT:              ckb-chain tests::dep_cell::test_package_txs_with_deps ---

running 1 test
test tests::dep_cell::test_package_txs_with_deps has been running for over 60 seconds
test tests::dep_cell::test_package_txs_with_deps ... FAILED

failures:

failures:
    tests::dep_cell::test_package_txs_with_deps

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 45 filtered out; finished in 121.09s


--- STDERR:              ckb-chain tests::dep_cell::test_package_txs_with_deps ---
thread 'tests::dep_cell::test_package_txs_with_deps' panicked at 'assertion failed: test_now.elapsed().as_secs() < 120', chain/src/tests/dep_cell.rs:192:9
stack backtrace:
   0:        0x106037543 - std::backtrace_rs::backtrace::libunwind::trace::h3a0c717b60f51a7a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x106037543 - std::backtrace_rs::backtrace::trace_unsynchronized::h9335432fefe8ab97
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x106037543 - std::sys_common::backtrace::_print_fmt::hd4969dd20679c9f5
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x106037543 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h574028a0687b01b1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10605a42b - core::fmt::rt::Argument::fmt::h55a6886216a743b4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:        0x10605a42b - core::fmt::write::hc3a291ca045d4386
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:        0x106033318 - std::io::Write::write_fmt::hce33c3aef899c477
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:        0x10603733a - std::sys_common::backtrace::_print::h9cb3bdde0b8af541
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10603733a - std::sys_common::backtrace::print::hec404ce64d885bc1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x1060391a5 - std::panicking::default_hook::{{closure}}::hb702376be934f723
  10:        0x106038faf - std::panicking::default_hook::he55b66a35bee68d8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:        0x106039643 - std::panicking::rust_panic_with_hook::hcabbae61abda3f7a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:        0x106039522 - std::panicking::begin_panic_handler::{{closure}}::hb0d2e10207b82ddc
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:595:13
  13:        0x106037949 - std::sys_common::backtrace::__rust_end_short_backtrace::h3fbd78d34f010841
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:        0x10603929d - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:        0x1060b0313 - core::panicking::panic_fmt::heecc6c3994a0556d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:        0x1060b03a7 - core::panicking::panic::h9a75b20204a37420
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:117:5
  17:        0x104285243 - ckb_chain::tests::dep_cell::test_package_txs_with_deps::h8fbcdd5a44e65254
                               at /Users/runner/work/ckb/ckb/chain/src/tests/dep_cell.rs:192:9
  18:        0x10427e719 - ckb_chain::tests::dep_cell::test_package_txs_with_deps::{{closure}}::hc946651fdb8f52da
                               at /Users/runner/work/ckb/ckb/chain/src/tests/dep_cell.rs:73:33
  19:        0x10428c9e8 - core::ops::function::FnOnce::call_once::h1c80881882d1fda1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  20:        0x104315ea2 - core::ops::function::FnOnce::call_once::hfea9e931317d4af9
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  21:        0x104315ea2 - test::__rust_begin_short_backtrace::h0867ba78eb40e8ba
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:655:18
  22:        0x1042e2461 - test::run_test::{{closure}}::he68f58ae8e9f4288
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:646:30
  23:        0x1042e2461 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he69d0c2148430b5e
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  24:        0x104314bd4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h56656d985a0790a7
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  25:        0x104314bd4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf9c[9432](https://github.com/nervosnetwork/ckb/actions/runs/6639559667/job/18038179855#step:4:9433)ff1025e85
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic/unwind_safe.rs:271:9
  26:        0x104314bd4 - std::panicking::try::do_call::hd2097739cadf3dea
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  27:        0x104314bd4 - std::panicking::try::hafe57032ad2b4e5c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  28:        0x104314bd4 - std::panic::catch_unwind::h5e7f52beb960fd87
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  29:        0x104314bd4 - test::run_test_in_process::h880a4a981a359133
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:678:27
  30:        0x104314bd4 - test::run_test::run_test_inner::{{closure}}::h00493900c74f53ca
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:572:39
  31:        0x1042dc8d1 - test::run_test::run_test_inner::{{closure}}::hee052bd9d6737e5b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/test/src/lib.rs:599:37
  32:        0x1042dc8d1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h693aa0e8dfe17dfb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:135:18
  33:        0x1042e24eb - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h15b34d1cf102bc5f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/mod.rs:529:17
  34:        0x1042e24eb - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h73c61fdd3f4175f0
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panic/unwind_safe.rs:271:9
  35:        0x1042e24eb - std::panicking::try::do_call::h4567304002a8fd54
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  36:        0x1042e24eb - std::panicking::try::h369daa30ad73e004
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  37:        0x1042e24eb - std::panic::catch_unwind::h67991b129fe5db35
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  38:        0x1042e24eb - std::thread::Builder::spawn_unchecked_::{{closure}}::h633dde3a89d10b5f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/thread/mod.rs:528:30
  39:        0x1042e24eb - core::ops::function::FnOnce::call_once{{vtable.shim}}::hefd34d7e8e4857b0
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  40:        0x10603efd9 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6f354cff5fe571f7
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  41:        0x10603efd9 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h00b999831daad24b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1985:9
  42:        0x10603efd9 - std::sys::unix::thread::Thread::new::thread_start::h29e24d4012c01df0
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7fff206548fc - __pthread_start

error: test run failed
make: *** [test] Error 100
```

### Expected Behavior

All unit tests should pass successfully

**Comment by rhomanone** [comment]
okey

**Comment by chenyukang** [comment]
emm, I can not reproduce it locally.
