### ISSUE TITLE
main ERROR panic  thread 'main' panicked at 'Failed to open rocksdb: Error { message: "IO error: While lock file: /var/lib/ckb/data/indexer/store/LOCK: Resource temporarily unavailable" }': util/indexer/src/store/rocksdb.rs:20

### ISSUE THREAD

**Issue by guomaoqiu** [nervosnetwork/ckb#4577]
## Bug Report

The following error occurred after the service restarted:

I still can't solve the problem after trying to delete the LOCK file. Please help me check it out.

### Environment

- **CKB version**:  0.117.0
- **Chain**: mainnet
- **Operating system**: Container
- **Arch**: x64 [the output of `uname -a`]
- **Installation**: [GitHub Release, Built from source]

### Additional context/Screenshots
```
Defaulted container "mainnet-ckb" out of: mainnet-ckb
+ cd /var/lib/ckb
+ ckb init --chain mainnet
Config files already exist; use --force to overwrite.
+ true
+ ckb migrate --force
+ ckb run
2024-08-09 19:18:29.062 +00:00 main INFO sentry  sentry is disabled
2024-08-09 19:18:29.156 +00:00 main INFO ckb_app_config  assume_valid_target set to 0x84ef5fe7cbf4242bdcac76326aa33f15b9cc41958e9d891157b8a6066dad0f31
2024-08-09 19:18:29.156 +00:00 main INFO ckb_bin::subcommand::run  ckb version: 0.117.0 (4920ecf 2024-07-29)
2024-08-09 19:18:29.156 +00:00 main INFO ckb_bin::subcommand::run  run rpc server with 2 threads
2024-08-09 19:18:29.156 +00:00 main INFO ckb_launcher  Miner is disabled; edit ckb.toml to enable it
2024-08-09 19:18:29.422 +00:00 main INFO ckb_memory_tracker::process  track current process: disable
2024-08-09 19:18:29.422 +00:00 main INFO ckb_launcher  chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2024-08-09 19:18:29.422 +00:00 main INFO ckb_sync::types  header_map.memory_limit 256MB
2024-08-09 19:18:29.438 +00:00 main INFO ckb_sync::types  assume valid target is already in db, CKB will do full verification from now on
2024-08-09 19:18:29.439 +00:00 main INFO ckb_network::network  Loading the peer store. This process may take a few seconds to complete.
2024-08-09 19:18:29.464 +00:00 GlobalRt-1 INFO ckb_network::network  Listen on address: /ip4/0.0.0.0/tcp/8115
2024-08-09 19:18:29.464 +00:00 GlobalRt-1 INFO ckb_network::network  p2p service event: ListenStarted { address: "/ip4/0.0.0.0/tcp/8115" }
2024-08-09 19:18:29.646 +00:00 GlobalRt-1 INFO ckb_filter  FilterProtocol.connected peer=SessionId(1)
2024-08-09 19:18:29.646 +00:00 GlobalRt-1 INFO ckb_relay  RelayProtocol(3).connected peer=SessionId(1)
2024-08-09 19:18:29.646 +00:00 GlobalRt-1 INFO ckb_sync::synchronizer  SyncProtocol.connected peer=SessionId(1)
2024-08-09 19:18:29.646 +00:00 GlobalRt-1 INFO ckb_light_client_protocol_server  LightClient(3).connected peer=SessionId(1)
2024-08-09 19:18:29.748 +00:00 GlobalRt-1 INFO ckb_relay  RelayProtocol(3).connected peer=SessionId(2)
2024-08-09 19:18:29.748 +00:00 GlobalRt-1 INFO ckb_sync::synchronizer  SyncProtocol.connected peer=SessionId(2)
2024-08-09 19:18:29.748 +00:00 GlobalRt-1 INFO ckb_light_client_protocol_server  LightClient(3).connected peer=SessionId(2)
2024-08-09 19:18:29.748 +00:00 GlobalRt-4 INFO ckb_filter  FilterProtocol.connected peer=SessionId(2)
2024-08-09 19:18:29.819 +00:00 main ERROR panic  thread 'main' panicked at 'Failed to open rocksdb: Error { message: "IO error: While lock file: /var/lib/ckb/data/indexer/store/LOCK: Resource temporarily unavailable" }': util/indexer/src/store/rocksdb.rs:20   0: ckb_logger_service::setup_panic_logger::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   7: ckb_indexer::service::IndexerService::new
   8: ckb_rpc::service_builder::ServiceBuilder::enable_indexer
   9: ckb_launcher::Launcher::start_network_and_rpc
  10: ckb_bin::subcommand::run::run
  11: ckb_bin::run_app_inner
  12: ckb_bin::run_app
  13: ckb::main
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: std::rt::lang_start
  16: __libc_start_main
  17: _start

2024-08-09 19:18:29.826 +00:00 GlobalRt-0 INFO ckb_relay  RelayProtocol(3).connected peer=SessionId(1)
2024-08-09 19:18:29.826 +00:00 GlobalRt-0 INFO ckb_relay  RelayProtocol(3).connected peer=SessionId(2)
```

**Comment by eval-exec** [comment]
> I still can't solve the problem after trying to delete the LOCK file. Please help me check it out.

Which LOCK file did you delete?

**Comment by guomaoqiu** [comment]
> > I still can't solve the problem after trying to delete the LOCK file. Please help me check it out.
> 
> Which LOCK file did you delete?

```/var/lib/ckb/data/indexer/store/LOCK```

**Comment by eval-exec** [comment]
> > > I still can't solve the problem after trying to delete the LOCK file. Please help me check it out.
> > 
> > 
> > Which LOCK file did you delete?
> 
> `/var/lib/ckb/data/indexer/store/LOCK`

After deleting /var/lib/ckb/data/indexer/store/LOCK, what error message do you see when starting CKB again?

**Comment by guomaoqiu** [comment]
> > > > I still can't solve the problem after trying to delete the LOCK file. Please help me check it out.
> > > 
> > > 
> > > Which LOCK file did you delete?
> > 
> > 
> > `/var/lib/ckb/data/indexer/store/LOCK`
> 
> After deleting /var/lib/ckb/data/indexer/store/LOCK, what error message do you see when starting CKB again?

Sorry, I seem to have described it wrong. I deleted `/var/lib/ckb/data/db/LOCK`. When I first discovered it, the log showed this.
```
Defaulted container "mainnet-ckb" out of: mainnet-ckb, ckb-nginx
+ cd /var/lib/ckb
+ ckb init --chain mainnet
Config files already exist; use --force to overwrite.
+ true
+ ckb migrate --force
Migration error Internal(DataCorrupted(failed to open the database: IO error: While lock file: /var/lib/ckb/data/db/LOCK: Resource temporarily unavailable))
```
So I tried to delete it, but it didn't work. Then just now I deleted `/var/lib/ckb/data/indexer/store/LOCK`, and it has returned to normal. I confused them.

**Comment by guomaoqiu** [comment]
Thanks @eval-exec

**Comment by guomaoqiu** [comment]
Hello, @eval-exec 
I have encountered a similar problem as above. 
Due to excessive service memory usage, the CKB node service restarted and the following error occurred. 
When I tried the same steps as above(Delete all LOCK files under the data directory), 
I found that the problem could not be solved.
 What suggestions do you have?  

Startup Log:
```
+ cd /var/lib/ckb
+ ckb init --chain mainnet
Config files already exist, use --force to overwrite.
+ true
+ ckb migrate --force
migrate error Internal(DataCorrupted(DB corrupted))
```
The current ckb version is: `nervos/ckb:v0.105.1`

**Comment by eval-exec** [comment]
@guomaoqiu What error do you get when you run `ckb run`? Could you share the error logs for further troubleshooting?

**Comment by guomaoqiu** [comment]
> @guomaoqiu What error do you get when you run `ckb run`? Could you share the error logs for further troubleshooting?

hi, when I start it manually, only the following output is:

```
+ cd /var/lib/ckb
+ ckb init --chain mainnet
Config files already exist, use --force to overwrite.
+ true
+ ckb migrate --force
migrate error Internal(DataCorrupted(DB corrupted))
```

**Comment by eval-exec** [comment]
You can start syncing from scratch, which might take several hours. DB corrupted can't be recovered now.

> Due to excessive service memory usage
Could you provide more details about the situation? When did the memory usage start increasing, and by how much did it grow?

**Comment by guomaoqiu** [comment]
> Are the error messages for `ckb run` and `ckb migrate --force` the same?
> 
> You can start syncing from scratch, which might take several hours. DB corrupted can't be recovered now.
> 
> > Due to excessive service memory usage
> 
> Could you provide more details about the situation? When did the memory usage start increasing, and by how much did it grow?

From this graph, we can see that the memory usage of the CKB node service is not too much. Since the container we use runs other services, the server is restarted, that is, the ckb node container is also restarted.
![image](https://github.com/user-attachments/assets/74aa90bd-ad35-490b-a458-7411651d6570)

**Comment by guomaoqiu** [comment]
> Are the error messages for `ckb run` and `ckb migrate --force` the same?
> 
> You can start syncing from scratch, which might take several hours. DB corrupted can't be recovered now.
> 
> > Due to excessive service memory usage
> 
> Could you provide more details about the situation? When did the memory usage start increasing, and by how much did it grow?

OK, I'll start syncing from the beginning. Thank you for your support.
